// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Satellite.Persistence.Database;

namespace Satellite.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210127210915_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Satellite")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Satellite.Domain.Satellite", b =>
                {
                    b.Property<int>("SatelliteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("CoordinateX")
                        .HasColumnType("float");

                    b.Property<double>("CoordinateY")
                        .HasColumnType("float");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SatelliteId");

                    b.HasIndex("SatelliteId");

                    b.ToTable("Satellites");

                    b.HasData(
                        new
                        {
                            SatelliteId = 1,
                            CoordinateX = -500.0,
                            CoordinateY = -200.0,
                            Distance = 0.0,
                            Name = "Kenobi"
                        },
                        new
                        {
                            SatelliteId = 2,
                            CoordinateX = -100.0,
                            CoordinateY = -100.0,
                            Distance = 0.0,
                            Name = "Skywalker"
                        },
                        new
                        {
                            SatelliteId = 3,
                            CoordinateX = 500.0,
                            CoordinateY = 100.0,
                            Distance = 0.0,
                            Name = "Sato"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
